### ISSUE TITLE
Appdata screenshot provides Windows snapshot

### ISSUE THREAD

**Issue by cicku** [Faster3ck/Ascii-Design#5]
Hi,

Appdata is useful for desktop users(particularly GNOME), I don't want to receive complaints about the wrong screenshot when they are using Linux.

I hope you can remake the screenshot.

Thanks.

**Comment by Faster3ck** [comment]
Hi,

Many thanks for reporting the problem. I didn't realize that i've used the wrong screenshot.
I've just fixed it.
